<a href="https://colab.research.google.com/github/Ryan-M-Smith/CS315/blob/main/HW09/encryption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [184]:
import numpy as np
import math

In [185]:
#
# Make a Caesar square from a message
#

input_str = "hheieotrk"
letters = [l for l in input_str]
#letters = list(map(ord, letters))

matrix = np.array(letters).reshape(3, 3)
matrix = matrix.transpose()
print(matrix)

[['h' 'i' 't']
 ['h' 'e' 'r']
 ['e' 'o' 'k']]


In [186]:
#
# Solve a Caesar cipher
#

ciphertext = [104, 105, 97, 108, 108]
plaintext = list(map(chr, ciphertext))
print(" ".join(plaintext))

h i a l l


In [187]:
#
# Solve a Caesar cipher with a shift
#

shift = 3
ciphertext = [107, 104, 124, 100, 111, 111]
shifted = list(map(lambda x: x - shift, ciphertext))
plaintext = list(map(chr, shifted))
print(" ".join(plaintext))

h e y a l l


In [188]:
input_str = "heyall"

# Calculate the next perfect square size for the matrix
current_len = len(input_str)
size = int(math.ceil(math.sqrt(current_len)))

# Pad the string to the calculated perfect square length
target_len = size * size
padding_needed = target_len - current_len
padded = input_str + 'x' * padding_needed # Using 'x' as padding character

letters = [l for l in padded]
letters = list(map(ord, letters))

# Calculate
A = np.random.randint(low=0, high=5, size=(size, size))
B = np.array(letters).reshape(size, size)
C = np.dot(A, B)

print(f"A = {A}")
print(f"B = {B}")
print(f"C = {C}")

A = [[2 1 4]
 [0 3 2]
 [1 0 0]]
B = [[104 101 121]
 [ 97 108 108]
 [120 120 120]]
C = [[785 790 830]
 [531 564 564]
 [104 101 121]]
